title: BLOGS
author: Sam Fu
navbar-links:
  Resources:
    - Learn markdown: 'https://www.markdowntutorial.com/'
    - Beautiful Jekyll: 'https://beautifuljekyll.com'
    About Me: aboutme
avatar: /assets/img/avatar-icon.png
round-avatar: true
social-network-links:
  email: fxy312@126.com
  rss: true
#   facebook: deanattali
  github: https://github.com/8fxy
#   twitter: daattali
#   patreon: DeanAttali
#   youtube: c/daattali
rss-description: Some Boring Blogs
# share-links-active:
#   twitter: true
#   facebook: true
#   linkedin: true
#   vk: false
url-pretty: blog.8fxy.cn
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
navbar-col: '#EAEAEA'
navbar-text-col: '#404040'
navbar-border-col: '#DDDDDD'
page-col: '#FFFFFF'
text-col: '#404040'
link-col: '#008AFF'
hover-col: '#0085A1'
footer-col: '#EAEAEA'
footer-text-col: '#777777'
footer-link-col: '#404040'
footer-hover-col: '#0085A1'
date_format: '%B %-d, %Y'
timezone: America/Toronto
markdown: kramdown
highlighter: rouge
permalink: '/:year-:month-:day-:title/'
paginate: 5
kramdown:
  input: GFM
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      social-share: true
  - scope:
      path: ''
    values:
      layout: page
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
